package com.mikael.lan

import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.Image
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.mikael.lan.data.Status
import com.mikael.lan.ui.MainViewModel

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { MikaelLanApp() } }
}

@Composable fun MikaelLanApp(vm: MainViewModel = viewModel()) {
    val network by vm.network.collectAsState(); val diagnostics by vm.diagnostics.collectAsState(); val worlds by vm.worlds.collectAsState(); val savedNetworks by vm.savedNetworks.collectAsState(); val publicNetworks by vm.publicNetworks.collectAsState(); val settings by vm.settings.collectAsState(); val requests by vm.joinRequests.collectAsState(); var screen by remember { mutableStateOf("home") }
    MaterialTheme(colorScheme = darkColorScheme(primary = Color(0xFF8D91FF), background = Color(0xFF10111A), surface = Color(0xFF1A1B27))) {
        Surface(Modifier.fillMaxSize()) { Column(Modifier.padding(20.dp)) {
            Text("MikaelLAN", style = MaterialTheme.typography.headlineLarge); Text("LAN virtual para jogar pela Internet", color = Color.LightGray)
            Spacer(Modifier.height(18.dp))
            when (screen) {
                "home" -> Home(network?.name, network?.peers?.size ?: 0, { screen = "create" }, { screen = "join" }, { screen = "saved" }, { screen = "public" }, { screen = "diagnostics" })
                "create" -> Create({ name, pass -> runCatching { vm.createNetwork(name, pass) }.onSuccess { screen = "network" } }, { screen = "home" })
                "join" -> Join({ name, pass -> runCatching { vm.joinNetwork(name, pass) }.onSuccess { screen = "network" } }, { screen = "home" })
                "network" -> NetworkScreen(network, worlds, vm, { screen = "home" }, { screen = "diagnostics" }, { screen = "settings" })
                "settings" -> NetworkSettingsScreen(settings, requests, vm, { screen = "network" })
                "saved" -> SavedNetworks(savedNetworks, vm, { screen = "home" }, { screen = "network" })
                "public" -> PublicNetworks(publicNetworks, vm, { screen = "home" }, { screen = "network" })
                else -> Diagnostics(diagnostics, { screen = "home" })
            }
        } }
    }
}

@Composable private fun Home(name: String?, count: Int, create: () -> Unit, join: () -> Unit, networks: () -> Unit, public: () -> Unit, diagnostics: () -> Unit) { Image(painterResource(com.mikael.lan.R.drawable.mikaellan_logo), "Logo MikaelLAN", Modifier.fillMaxWidth().height(150.dp)); Text("MikaelLAN", style = MaterialTheme.typography.headlineLarge); StatusCard(if (name == null) "Não conectado" else "Conectado", name ?: "Nenhuma rede ativa", count); Spacer(Modifier.height(18.dp)); Button(create, Modifier.fillMaxWidth()) { Text("CRIAR REDE") }; Spacer(Modifier.height(10.dp)); OutlinedButton(join, Modifier.fillMaxWidth()) { Text("ENTRAR EM REDE") }; TextButton(networks, Modifier.fillMaxWidth()) { Text("MINHAS REDES") }; TextButton(public, Modifier.fillMaxWidth()) { Text("REDES PÚBLICAS") }; TextButton(diagnostics, Modifier.fillMaxWidth()) { Text("DIAGNÓSTICO") } }

@Composable private fun Create(done: (String, String) -> Unit, back: () -> Unit) { var name by remember { mutableStateOf("") }; var pass by remember { mutableStateOf("") }; Title("Criar rede", back); OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Nome da rede *") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Spacer(Modifier.height(10.dp)); OutlinedTextField(value = pass, onValueChange = { pass = it }, label = { Text("Senha da rede *") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Spacer(Modifier.height(12.dp)); Text("Compartilhe o nome e a senha somente com os jogadores convidados.", color = Color.LightGray); Spacer(Modifier.height(18.dp)); Button({ done(name, pass) }, enabled = name.isNotBlank() && pass.length >= 4, modifier = Modifier.fillMaxWidth()) { Text("CRIAR E CONECTAR") } }
@Composable private fun Join(done: (String, String) -> Unit, back: () -> Unit) { var name by remember { mutableStateOf("") }; var pass by remember { mutableStateOf("") }; Title("Entrar em rede", back); OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Nome da rede *") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Spacer(Modifier.height(10.dp)); OutlinedTextField(value = pass, onValueChange = { pass = it }, label = { Text("Senha da rede *") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Spacer(Modifier.height(18.dp)); Button({ done(name, pass) }, enabled = name.isNotBlank() && pass.length >= 4, modifier = Modifier.fillMaxWidth()) { Text("ENTRAR NA REDE") } }

@Composable private fun NetworkScreen(n: com.mikael.lan.data.LanNetwork?, worlds: List<com.mikael.lan.data.LanWorld>, vm: MainViewModel, back: () -> Unit, diag: () -> Unit, settings: () -> Unit) { Title(n?.name ?: "Rede", back); StatusCard(if (n?.connected == true) "Conectado" else "Desconectado", "IP virtual: ${n?.virtualIp ?: "-"}", n?.peers?.size ?: 0); Spacer(Modifier.height(14.dp)); Text("Mundos LAN disponíveis", style = MaterialTheme.typography.titleLarge); if (worlds.isEmpty()) Text("Nenhum mundo encontrado. Peça ao host para abrir o mundo para LAN.", color = Color.LightGray) else worlds.forEach { world -> Card(Modifier.fillMaxWidth().padding(vertical = 6.dp)) { Column(Modifier.padding(12.dp)) { Text("● ${world.name}"); Text("Host: ${world.hostName} • ${world.latencyMs} ms", color = Color.LightGray); Button({ }, Modifier.fillMaxWidth()) { Text("ENTRAR NO MUNDO") } } } }; Text("Usuários conectados", style = MaterialTheme.typography.titleLarge); n?.peers?.forEach { peer -> Card(Modifier.fillMaxWidth().padding(vertical = 4.dp)) { Column(Modifier.padding(10.dp)) { Text("${peer.name} • ${peer.virtualIp}"); Text(peer.role, color = Color.LightGray); Row { if (peer.role == "Membro") TextButton({ vm.promotePeer(peer) }) { Text("PROMOVER") } else TextButton({ vm.demotePeer(peer) }) { Text("REBAIXAR") }; TextButton({ vm.banPeer(peer) }) { Text("BANIR") } } } } }; Text("O IP só é necessário como alternativa: ${n?.virtualIp ?: "10.10.0.x"}:25565", color = Color.LightGray); Spacer(Modifier.height(12.dp)); Button({ settings() }, Modifier.fillMaxWidth()) { Text("CONFIGURAÇÕES DA REDE") }; Button({ vm.saveCurrentNetwork() }, Modifier.fillMaxWidth()) { Text("SALVAR REDE") }; OutlinedButton({ vm.disconnect() }, Modifier.fillMaxWidth()) { Text("DESCONECTAR") }; Button({ vm.discoverWorlds() }, Modifier.fillMaxWidth()) { Text("ATUALIZAR MUNDOS") }; Button({ vm.runDiagnostics(); diag() }, Modifier.fillMaxWidth()) { Text("DIAGNÓSTICO") }; TextButton(back, Modifier.fillMaxWidth()) { Text("VOLTAR") } }

@Composable private fun NetworkSettingsScreen(settings: com.mikael.lan.data.NetworkSettings, requests: List<com.mikael.lan.data.JoinRequest>, vm: MainViewModel, back: () -> Unit) { var auto by remember(settings.autoAccept) { mutableStateOf(settings.autoAccept) }; var discovery by remember(settings.allowWorldDiscovery) { mutableStateOf(settings.allowWorldDiscovery) }; var maxText by remember(settings.maxPlayers) { mutableStateOf(settings.maxPlayers.toString()) }; Title("Configurações da rede", back); Text("Visibilidade", style = MaterialTheme.typography.titleLarge); if (settings.isPublic) OutlinedButton({ vm.unpublishCurrentNetwork() }, Modifier.fillMaxWidth()) { Text("RETIRAR DA REDE PÚBLICA") } else Button({ vm.publishCurrentNetwork() }, Modifier.fillMaxWidth()) { Text("TORNAR REDE PÚBLICA") }; Text("Você pode publicar no máximo 3 redes neste aparelho.", color = Color.LightGray); Spacer(Modifier.height(12.dp)); Text("Limite da rede", style = MaterialTheme.typography.titleLarge); OutlinedTextField(value = maxText, onValueChange = { value -> if (value.all { it.isDigit() } && value.length <= 3) { maxText = value; value.toIntOrNull()?.coerceIn(2, 250)?.let { vm.updateSettings(settings.copy(maxPlayers = it)) } } }, label = { Text("Máximo de jogadores (2 a 250)") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Spacer(Modifier.height(12.dp)); Text("Entrada de jogadores", style = MaterialTheme.typography.titleLarge); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("Aceitar automaticamente"); Switch(auto, { auto = it; vm.updateSettings(settings.copy(autoAccept = it)) }) }; Text(if (auto) "Novos jogadores entram direto com nome e senha." else "Novos jogadores precisam de aprovação do criador.", color = Color.LightGray); Spacer(Modifier.height(12.dp)); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("Mostrar mundos LAN"); Switch(discovery, { discovery = it; vm.updateSettings(settings.copy(allowWorldDiscovery = it)) }) }; Spacer(Modifier.height(18.dp)); Text("Pedidos pendentes (${requests.size})", style = MaterialTheme.typography.titleLarge); if (requests.isEmpty()) Text("Nenhum pedido aguardando.", color = Color.LightGray) else requests.forEach { request -> Card(Modifier.fillMaxWidth().padding(vertical = 5.dp)) { Column(Modifier.padding(12.dp)) { Text(request.playerName); Row { Button({ vm.approveRequest(request) }) { Text("ACEITAR") }; Spacer(Modifier.width(8.dp)); OutlinedButton({ vm.denyRequest(request) }) { Text("RECUSAR") } } } } }; Spacer(Modifier.height(14.dp)); Text("Somente o criador deve compartilhar a senha e administrar banimentos.", color = Color.LightGray) }
@Composable private fun SavedNetworks(networks: List<com.mikael.lan.data.LanNetwork>, vm: MainViewModel, back: () -> Unit, openNetwork: () -> Unit) { Title("Minhas redes", back); if (networks.isEmpty()) Text("Nenhuma rede salva ainda. Conecte-se a uma rede e toque em Salvar rede.", color = Color.LightGray) else LazyColumn { items(networks) { saved -> Card(Modifier.fillMaxWidth().padding(vertical = 6.dp)) { Column(Modifier.padding(12.dp)) { Text(saved.name, style = MaterialTheme.typography.titleMedium); Text("Rede salva neste aparelho", color = Color.LightGray); Button({ vm.reconnect(saved); openNetwork() }, Modifier.fillMaxWidth()) { Text("CONECTAR") } } } } } }
@Composable private fun PublicNetworks(networks: List<com.mikael.lan.data.LanNetwork>, vm: MainViewModel, back: () -> Unit, openNetwork: () -> Unit) { Title("Redes públicas", back); Text("Redes abertas para descoberta. O limite de publicação por aparelho é 3.", color = Color.LightGray); Spacer(Modifier.height(10.dp)); LazyColumn { items(networks) { public -> Card(Modifier.fillMaxWidth().padding(vertical = 6.dp)) { Column(Modifier.padding(12.dp)) { Text(public.name, style = MaterialTheme.typography.titleMedium); Text("Jogadores: ${public.peers.size} • Entrada conforme regras da rede", color = Color.LightGray); Button({ vm.reconnect(public); openNetwork() }, Modifier.fillMaxWidth()) { Text("VER REDE") } } } } } }
@Composable private fun Diagnostics(items: List<com.mikael.lan.data.Diagnostic>, back: () -> Unit) { Title("Diagnóstico", back); if (items.isEmpty()) Text("Nenhum diagnóstico executado.") else LazyColumn { items(items) { d -> val icon = if (d.status == Status.OK) "✓" else if (d.status == Status.WARN) "!" else "×"; Text("$icon ${d.label}: ${d.detail}", Modifier.padding(vertical = 9.dp)) } }; Spacer(Modifier.height(14.dp)); Text("A descoberta automática multicast pode ser limitada pelo Android; use IP virtual + porta quando necessário.", color = Color.LightGray) }
@Composable private fun StatusCard(status: String, network: String, count: Int) { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp)) { Text("● $status", color = Color(0xFF66E38C)); Text("Rede: $network"); Text("Jogadores: $count") } } }
@Composable private fun Title(title: String, back: () -> Unit) { TextButton(back) { Text("← Voltar") }; Text(title, style = MaterialTheme.typography.headlineMedium); Spacer(Modifier.height(12.dp)) }
